=== Quazawaza/HiHproject1/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:simpleType name="YearType">
        <xs:restriction base="xs:gYear">
            <xs:minInclusive value="1900"/>
            <xs:maxInclusive value="2025"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="LinkType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(https?://.+|(\.\/|\.\.\/).+|[a-zA-Z]:\\.+)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="NameType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DescriptionType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="1000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="GenreType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Metal"/>
            <xs:enumeration value="Nu-Metal"/>
            <xs:enumeration value="Rock"/>
            <xs:enumeration value="Elektroniczna"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="InstrumentType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="InstrumentListType">
        <xs:sequence>
            <xs:element name="Instrument" type="InstrumentType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AlbumType">
        <xs:sequence>
            <xs:element name="Title" type="NameType"/>
            <xs:element name="Year" type="YearType"/>
            <xs:element name="Cover" type="LinkType"/>
        </xs:sequence>
        <xs:attribute name="EPka" type="xs:boolean" use="optional"/>
    </xs:complexType>

    <xs:complexType name="MemberType">
        <xs:sequence>
            <xs:element name="Name" type="NameType"/>
            <xs:element name="Instruments" type="InstrumentListType"/>
            <xs:element name="YearsActive">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{4}(-\d{4}|-teraz)?"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Photo" type="LinkType"/>
        </xs:sequence>
        <xs:attribute name="role">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Wokalista"/>
                    <xs:enumeration value="Gitarzysta"/>
                    <xs:enumeration value="Basista"/>
                    <xs:enumeration value="Perkusista"/>
                    <xs:enumeration value="Klawiszowiec"/>
                    <xs:enumeration value="Inna"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="LinksType">
        <xs:sequence>
            <xs:element name="OfficialWebsite" type="LinkType"/>
            <xs:element name="YouTubeChannel" type="LinkType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BandType">
        <xs:sequence>
            <xs:element name="Members">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Member" type="MemberType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Albums">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Album" type="AlbumType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Genre" type="GenreType"/>
            <xs:element name="Description" type="DescriptionType"/>
            <xs:group ref="SocialsGroup"/>
        </xs:sequence>
    </xs:complexType>

    <xs:group name="SocialsGroup">
        <xs:sequence>
            <xs:element name="Page" type="LinkType" minOccurs="0"/>
            <xs:element name="Youtube" type="LinkType" minOccurs="0"/>
        </xs:sequence>
    </xs:group>


    <xs:complexType name="ContactType">
        <xs:sequence>
            <xs:group ref="ContactGroup"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ExtendedBandType">
        <xs:complexContent>
            <xs:extension base="BandType">
                <xs:sequence>
                    <xs:element name="Awards" type="xs:string" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="Bands">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Band" type="BandType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Quazawaza/HiHproject1/xml/Muzycy.xml
<?xml version="1.0" encoding="UTF-8"?>
<Bands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <Band JestKultowy="true">
        <Members>
            <Member role="Wokalista" JestKultowy="true">
                <Name>Emily Armstrong</Name>
                <Instruments>
                    <Instrument>Wokal prowadzący</Instrument>
                </Instruments>
                <YearsActive>2024-Present</YearsActive>
                <Photo>emily_armstrong.jpg</Photo>
            </Member>
            <Member role="Wokalista, Rap, Gitara rytmiczna, Keyboard, Programowanie" JestKultowy="true">
                <Name>Mike Shinoda</Name>
                <Instruments>
                    <Instrument>Wokal wspierający</Instrument>
                    <Instrument>Rap</Instrument>
                    <Instrument>Gitara rytmiczna</Instrument>
                    <Instrument>Keyboard</Instrument>
                    <Instrument>Programowanie</Instrument>
                </Instruments>
                <YearsActive>1996-Present</YearsActive>
                <Photo>mike_shinoda.jpg</Photo>
            </Member>
            <Member role="Gitara prowadząca, Gitara rytmiczna, Programowanie" JestKultowy="true">
                <Name>Brad Delson</Name>
                <Instruments>
                    <Instrument>Gitara prowadząca</Instrument>
                    <Instrument>Gitara rytmiczna</Instrument>
                    <Instrument>Programowanie</Instrument>
                </Instruments>
                <YearsActive>1996-Present</YearsActive>
                <Photo>brad_delson.jpg</Photo>
            </Member>
            <Member role="Gitara basowa" JestKultowy="true">
                <Name>Dave Farrell</Name>
                <Instruments>
                    <Instrument>Gitara basowa</Instrument>
                </Instruments>
                <YearsActive>1996-Present</YearsActive>
                <Photo>dave_farrell.jpg</Photo>
            </Member>
            <Member role="DJ, Turnatablizm, Instrumenty klawiszowe" JestKultowy="true">
                <Name>Joe Hahn</Name>
                <Instruments>
                    <Instrument>DJ</Instrument>
                    <Instrument>Turnatablizm</Instrument>
                    <Instrument>Instrumenty klawiszowe</Instrument>
                </Instruments>
                <YearsActive>1996-Present</YearsActive>
                <Photo>joe_hahn.jpg</Photo>
            </Member>
            <Member role="Perkusja" JestKultowy="false">
                <Name>Collin Brittain</Name>
                <Instruments>
                    <Instrument>Perkusja</Instrument>
                </Instruments>
                <YearsActive>2024-Present</YearsActive>
                <Photo>collin_brittain.jpg</Photo>
            </Member>

            <Member role="Wokalista" JestKultowy="true">
                <Name>Chester Bennington</Name>
                <Instruments>
                    <Instrument>Wokal prowadzący</Instrument>
                </Instruments>
                <YearsActive>1999-2017</YearsActive>
                <Photo>chester_bennington.jpg</Photo>
            </Member>
            <Member role="Perkusja, Instrumenty perkusyjne" JestKultowy="true">
                <Name>Rob Bourdon</Name>
                <Instruments>
                    <Instrument>Perkusja</Instrument>
                    <Instrument>Instrumenty perkusyjne</Instrument>
                </Instruments>
                <YearsActive>1996-2024</YearsActive>
                <Photo>rob_bourdon.jpg</Photo>
            </Member>
            <Member role="Wokalista" JestKultowy="false">
                <Name>Mark Wakefield</Name>
                <Instruments>
                    <Instrument>Wokal prowadzący</Instrument>
                </Instruments>
                <YearsActive>1996-1998</YearsActive>
                <Photo>mark_wakefield.jpg</Photo>
            </Member>
        </Members>
        <Albums>
            <Album EPka="false" JestKultowy="true">
                <Title>Hybrid Theory</Title>
                <Year>2000</Year>
                <Cover>cover_hybrid_theory.jpg</Cover>
            </Album>
            <Album EPka="false" JestKultowy="true">
                <Title>Meteora</Title>
                <Year>2003</Year>
                <Cover>cover_meteora.jpg</Cover>
            </Album>
            <Album EPka="false" JestKultowy="false">
                <Title>Minutes to Midnight</Title>
                <Year>2007</Year>
                <Cover>cover_minutes_to_midnight.jpg</Cover>
            </Album>
            <Album EPka="false" JestKultowy="false">
                <Title>A Thousand Suns</Title>
                <Year>2010</Year>
                <Cover>cover_a_thousand_suns.jpg</Cover>
            </Album>
            <Album EPka="false" JestKultowy="false">
                <Title>Living Things</Title>
                <Year>2012</Year>
                <Cover>cover_living_things.jpg</Cover>
            </Album>
            <Album EPka="false" JestKultowy="false">
                <Title>The Hunting Party</Title>
                <Year>2014</Year>
                <Cover>cover_the_hunting_party.jpg</Cover>
            </Album>
            <Album EPka="false" JestKultowy="false">
                <Title>One More Light</Title>
                <Year>2017</Year>
                <Cover>cover_one_more_light.jpg</Cover>
            </Album>
            <Album EPka="false" JestKultowy="false">
                <Title>From Zero</Title>
                <Year>2024</Year>
                <Cover>cover_from_zero.jpg</Cover>
            </Album>
        </Albums>
        <Genre>Nu-Metal</Genre>
        <Description>Linkin Park - amerykański zespół muzyczny wykonujący szeroko pojętą muzykę rockową i metalową. Powstał w 1996 roku w Agoura Hills w Kalifornii, a sławę zyskał w 2000 roku po wydaniu pierwszego albumu, Hybrid Theory. Od tego czasu Linkin Park stali się jedną z najpopularniejszych grup w historii muzyki.</Description>
        <Page>https://www.linkinpark.com</Page>
        <YouTube>https://www.youtube.com/user/linkinpark</YouTube>

    </Band>
</Bands>
